language: cpp

compiler:
  - gcc
  - clang

install:
 - sudo apt-get update
 - sudo apt-get install cmake gperf

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make

